### ISSUE TITLE
compatibility issue with jekyll 3.0.1

### ISSUE THREAD

**Issue by archersmind** [vormwald/joon#7] opened 2016-02-25 07:32 UTC
Hi

This is an awesome theme, but I not sure the `jekyll` version you're using, since it might be a compatibility issue here with `jekyll 3.0.1`.

Cause when I preview this theme with `jekyll server`, some of the components of the theme is missing:

![screenshot from 2016-02-25 15 23 59](https://cloud.githubusercontent.com/assets/1461331/13312755/0f6d1496-dbd4-11e5-8db8-f6f7756d15c3.png)

And I see a error message when I running `jekyll serve`:

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate`        gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

Thank you for this great theme.

**Comment by vormwald** [comment] 2016-02-26 03:56
Hey thanks so much for the feedback.  (Disclaimer, I can't claim any credit for the theme... I just ported it over :) 

I'm not sure why it was not rendering the proper elements since those were just deprecation warnings, but I confirmed it didnt' work on jekyll v3.

Just merged in a change (#8) including a proper gem file referencing github-pages. So that'll track whatever version of jekyll those guys are running.

Should solve the problems you were seeing.

Thanks again for the feedback, very helpful!

**Closed as completed by vormwald** 2016-02-26 03:56 UTC

**Comment by archersmind** [comment] 2016-02-26 07:52
@vormwald  Thanks for your reply, but it seems to be another problem caused by 5269287a .

After merge this change, I can always see below message whenever I'm trying to build this theme with     `jekyll b`

```
alan@joon$jekyll b
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find listen-3.0.6 in any of the sources (Bundler::GemNotFound)
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
    from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
    from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/bin/jekyll:9:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
```

`Gems` that you added in 5269287a are not found in this case.

I'm a totally newbie for `ruby` and web things, so I may not well demonstrate the issue here.

Thanks

**Comment by vormwald** [comment] 2016-02-26 16:24
2 things to try.

Make sure you `bundle install` with the new version. 
If it's still not working, try running the jekyll command prefixed by `bundle exec`  so `jekyll build` / `jekyll server`/etc, which ensures you use the gem versions specified in Gemfile.lock

**Comment by archersmind** [comment] 2016-02-28 05:32
@vormwald  It's working, maybe you should add `bundle install` command in the `README`. It's very helpful for users like me.

Thanks

**Comment by vormwald** [comment] 2016-02-29 18:40
Great suggestion, i'll do that.  Thanks again for reporting the issue!
